package com.jobtrack.entity;

public enum EventType {
    APPLICATION_SUBMITTED,
    CONFIRMATION_RECEIVED,
    ASSESSMENT_INVITE,
    ASSESSMENT_COMPLETED,
    INTERVIEW_INVITE,
    INTERVIEW_COMPLETED,
    OFFER_RECEIVED,
    OFFER_ACCEPTED,
    REJECTED,
    WITHDRAWN,
    NOTE_ADDED,
    STATUS_CHANGED_MANUALLY
}